# Generated by Django 2.1.5 on 2019-02-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bot_enable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(default='', max_length=24),
        ),
    ]
