# Generated by Django 2.1.5 on 2019-02-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='playername',
            field=models.CharField(default='', max_length=24),
        ),
    ]
