# Generated by Django 2.1.5 on 2019-02-18 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190218_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='bot_enable',
            new_name='bot_enabled',
        ),
    ]
