kind: pipeline
name: pipeline
steps:
- name: publish
  image: plugins/docker
  settings:
    repo: pingu/ogamebot
    tags: latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    status: [ success ]
    branch: [ master ]
- name: deploy
  image: pingu/drone-plugin-kontena:latest
  settings:
    kontena_url:
      from_secret: kontena_url
    kontena_token:
      from_secret: kontena_token
    kontena_grid:
      from_secret: kontena_grid
    kontena_file: kontena.yml
    kontena_stack: ogamebot
  when:
    status: [ success ]
    branch: [ master ]
