---
stack: vngu/ogame
version: '0.0.1'
description: ogame
services:
  bot:
    image: pingu/ogamebot:latest
    affinity:
      - node==grapefruit
    environment:
      - KONTENA_LB_INTERNAL_PORT=5000
      - KONTENA_LB_VIRTUAL_HOSTS=ogamebot.quving.com
      - TZ=Europe/Berlin
      - OGAMEBOT_MYSQL_HOST=mysql
      - OGAMEBOT_REDIS_HOST=redis
    links:
      - system/lb
      - mysql
      - redis
    secrets:
      - secret: SELENIUM_HUB_HOST
        name: SELENIUM_HUB_HOST
        type: env
      - secret: OGAMEBOT_SECRET_KEY
        name: OGAMEBOT_SECRET_KEY
        type: env
      - secret: OGAMEBOT_MYSQL_DB
        name: OGAMEBOT_MYSQL_DB
        type: env
      - secret: OGAMEBOT_MYSQL_USER
        name: OGAMEBOT_MYSQL_USER
        type: env
      - secret: OGAMEBOT_MYSQL_PASSWORD
        name: OGAMEBOT_MYSQL_PASSWORD
        type: env

  mysql:
    image: mysql:5.7.8
    instances: 1
    affinity:
      - node==grapefruit
    stateful: yes
    volumes:
      - /srv/ogamebot/mysql/5.7.8:/data/db
    links:
      - system/lb
    environment:
      - TZ=Europe/Berlin
      - MYSQL_USER=ogamebot
    secrets:
      - secret: OGAMEBOT_MYSQL_DB
        name: MYSQL_DATABASE
        type: env
      - secret: OGAMEBOT_MYSQL_USER
        name: MYSQL_USER
        type: env
      - secret: OGAMEBOT_MYSQL_PASSWORD
        name: MYSQL_PASSWORD
        type: env
      - secret: MYSQL_ROOT_PASSWORD
        name: MYSQL_ROOT_PASSWORD
        type: env

  redis:
    image: redis:latest
    instances: 1
    affinity:
      - node==grapefruit
    stateful: yes
    links:
      - system/lb
    environment:
      - TZ=Europe/Berlin

