---
stack: vngu/ogame
version: '0.0.1'
description: ogame
services:
  bot:
    image: pingu/ogamebot:latest
    affinity:
      - node==grapefruit
    environment:
      - KONTENA_LB_INTERNAL_PORT=5000
      - KONTENA_LB_VIRTUAL_HOSTS=ogamebot.quving.com
      - TZ=Europe/Berlin
      - OGAMEBOT_POSTGRES_HOST=postgres
      - OGAMEBOT_POSTGRES_USER=ogamebot
      - OGAMEBOT_POSTGRES_DB=ogamebot_db
      - OGAMEBOT_REDIS_HOST=redis
    links:
      - system/lb
      - postgres
      - redis
    secrets:
      - secret: SELENIUM_HUB_HOST
        name: SELENIUM_HUB_HOST
        type: env
      - secret: OGAMEBOT_SECRET_KEY
        name: OGAMEBOT_SECRET_KEY
        type: env
      - secret: OGAMEBOT_POSTGRES_PASSWORD
        name: OGAMEBOT_POSTGRES_PASSWORD
        type: env

  postgres:
    image: postgres:11
    instances: 1
    affinity:
      - node==grapefruit
    stateful: yes
    volumes:
      - /srv/ogamebot/postgres:/data/db
    links:
      - system/lb
    environment:
      - TZ=Europe/Berlin
      - POSTGRES_USER=ogamebot
      - POSTGRES_DB=ogamebot_db
    secrets:
      - secret: OGAMEBOT_POSTGRES_PASSWORD
        name: POSTGRES_PASSWORD
        type: env

  redis:
    image: redis:latest
    instances: 1
    affinity:
      - node==grapefruit
    stateful: yes
    links:
      - system/lb
    environment:
      - TZ=Europe/Berlin

