# Generated by Django 2.1.5 on 2019-02-21 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planet', '0001_initial'),
        ('mine', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IronMine',
            new_name='MetalMine',
        ),
    ]
