# Generated by Django 2.1.5 on 2019-02-27 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0002_auto_20190227_2355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mine',
            options={},
        ),
        migrations.RemoveField(
            model_name='mine',
            name='created',
        ),
    ]
