# Generated by Django 2.1.5 on 2019-02-21 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0002_auto_20190221_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mine',
            name='name',
            field=models.TextField(default='', max_length=24),
        ),
    ]
