# Generated by Django 2.1.5 on 2019-02-21 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0004_auto_20190221_0251'),
    ]

    operations = [
        migrations.CreateModel(
            name='FusionReactor',
            fields=[
                ('mine_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mine.Mine')),
            ],
            bases=('mine.mine',),
        ),
        migrations.CreateModel(
            name='SolarPowerstation',
            fields=[
                ('mine_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mine.Mine')),
            ],
            bases=('mine.mine',),
        ),
        migrations.CreateModel(
            name='SolarSatellite',
            fields=[
                ('mine_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mine.Mine')),
            ],
            bases=('mine.mine',),
        ),
        migrations.AlterModelOptions(
            name='mine',
            options={'ordering': ('created',)},
        ),
    ]
