# Generated by Django 2.1.5 on 2019-02-21 03:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0005_auto_20190221_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mine',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='mine',
            name='name',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AlterField(
            model_name='mine',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
