# Generated by Django 2.1.5 on 2019-02-21 03:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0006_auto_20190221_0332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mine',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='mine',
            name='uptimed_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 21, 3, 39, 12, 260514, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mine',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 21, 3, 39, 12, 260475, tzinfo=utc)),
        ),
    ]
