# Generated by Django 2.1.5 on 2019-02-21 21:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0007_auto_20190221_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mine',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mine',
            name='uptimed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
