# Generated by Django 2.1.5 on 2019-02-22 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mine', '0008_auto_20190221_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mine',
            name='planet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mines', to='planet.Planet'),
        ),
    ]
