# Generated by Django 2.1.5 on 2019-02-24 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal', models.FloatField(default=0)),
                ('crystal', models.FloatField(default=0)),
                ('deuterium', models.FloatField(default=0)),
                ('dark_matter', models.FloatField(default=0)),
                ('energy', models.FloatField(default=0)),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='planet.Planet')),
            ],
        ),
    ]
