# Generated by Django 2.1.5 on 2019-02-22 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20190221_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='planet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='planet.Planet'),
        ),
    ]
