# Generated by Django 2.1.7 on 2019-03-22 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='crawl_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bot',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
        ),
    ]
