# Generated by Django 2.1.7 on 2019-03-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20190322_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='bot_enabled',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='copy_mines_with_main_planet',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='crawl_enabled',
        ),
        migrations.AddField(
            model_name='bot',
            name='builder_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bot',
            name='crawler_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bot',
            name='stacker_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
