# Generated by Django 2.1.7 on 2019-03-21 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.CharField(default='', max_length=3)),
                ('y', models.CharField(default='', max_length=3)),
                ('z', models.CharField(default='', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=32)),
                ('is_main', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planets', to='account.Account')),
                ('coord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planet', to='planet.Coordinate')),
            ],
        ),
    ]
