# Generated by Django 2.1.5 on 2019-02-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.CharField(default='', max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=16)),
            ],
        ),
    ]
