# Generated by Django 2.1.5 on 2019-02-18 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_account_bot_enabled'),
        ('planet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='account',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
        ),
    ]
