# Generated by Django 2.1.7 on 2019-03-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='building',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planet',
            name='enable_builder',
            field=models.BooleanField(default=False),
        ),
    ]
