# Generated by Django 2.1.5 on 2019-02-24 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinate',
            name='x',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='y',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='z',
            field=models.CharField(default='', max_length=3),
        ),
    ]
