# Generated by Django 2.1.5 on 2019-02-24 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planet', '0002_auto_20190224_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='coord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planet', to='planet.Coordinate'),
        ),
    ]
