# Generated by Django 2.1.5 on 2019-02-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planet', '0002_auto_20190222_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
