# Generated by Django 2.1.7 on 2019-03-22 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planet', '0002_auto_20190322_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planet',
            old_name='enable_builder',
            new_name='builder_enabled',
        ),
    ]
