# Generated by Django 2.1.7 on 2019-03-22 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planet', '0003_auto_20190322_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planet',
            name='building',
        ),
    ]
