# Generated by Django 2.1.5 on 2019-02-27 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planet', '0004_auto_20190227_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
