# Generated by Django 2.1.5 on 2019-03-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planet', '0005_auto_20190227_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='name',
            field=models.CharField(default='', max_length=32),
        ),
    ]
